name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run tests
        run: make test

      - name: Build project
        run: make out/example

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-binary
          path: out/example
